name: OrangeFox Recovery Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Device Tree
        uses: actions/checkout@v4
        with:
          path: fox_12.1/device/xiaomi/tanzanite

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev \
            gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses-dev x11proto-core-dev \
            libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

      - name: Install Google Repo Tool
       run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+rx ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH
    
      - name: Sync OrangeFox Source & Build
        run: |
          export PATH="$HOME/bin:$PATH"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # 1. Sync OrangeFox 12.1 source directly
          git clone https://gitlab.com/OrangeFox/sync.git ~/OFRP_Sync
          cd ~/OFRP_Sync
          ./orangefox_sync.sh --branch 12.1 --path $GITHUB_WORKSPACE/fox_12.1

          # 2. Setup environment and compile
          cd $GITHUB_WORKSPACE/fox_12.1
          export ALLOW_MISSING_DEPENDENCIES=true
          export FOX_BUILD_DEVICE=tanzanite
          export LC_ALL="C"

          source build/envsetup.sh
          lunch twrp_tanzanite-eng || lunch omni_tanzanite-eng
          mka recoveryimage -j$(nproc --all)
          
